config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'robots#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :robots
  resources :bookings

  namespace :my do
    resources :robots, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :robot
  belongs_to :user
end

app/models/robot.rb
class Robot < ApplicationRecord
  has_many :bookings
  belongs_to :user
  validates :name, presence: true, uniqueness: true
  validates :functions, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings
  has_many :robots, through: :bookings
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index

  end

  def show

  end

  def new

  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.robot = @robot
    @booking.save

    redirect_to my_robots_path
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private
  def booking_params
    params.require(:booking).permit(:beginning_of_rental, :end_of_rental)
  end


end

app/controllers/my/robots_controller.rb
class My::RobotsController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController

def index
  if params[:query].present?
      @robots = Robot.where(functions: params[:query])
  else
      @robots = Robot.all
  end
end

def show
  @robot = Robot.find(params[:id])
  @booking = Booking.new
end

def new
  @robot = Robot.new

end

def create
  @robot = Robot.new(name: params[:name], functions: params[:functions], caracteristics: params[:caracteristics], price: params[:price])
  @robot.save
end

def edit

end

def update

end

def destroy
  @robot = Robot.find(params[:id])
  @robot.destroy
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Capsule-Corp</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/my/robots/index.html.erb
<div class="container">
  <div class="user-card">
    <div class="user-picture-and-button">

    </div>

    <div class="user-details">
      <h3><%= current_user.email %></h3>
    </div>
    <div>
      <% robots = current_user.robots %>
      <% robots.each do |robot| %>
        <h4> <%= robot.name %></h4><br>
      <% end %>
    </div>
  </div>
  <div>
  </div>
  <hr>
  <div class="robots-owned-or-bookings-maid">
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <h1>Capsule Corp.</h1>
  <h3>Sorry for the inconvenients. And happy hacking!</h3>
  <%= image_tag "serveimage.jpeg", alt: "robot", width: 900 %>
</div>

app/views/robots/index.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path 'robot-and-human-team.jpg' %>') no-repeat center; background-size: cover;">
  <div class="banner-content">
    <h1>CAPSULE CORPORATION</h1>
    <p>More human than human, every days we are building a better world for you.</p>
    <a href="#dernieres-nouvelles" class="btn btn-info">Start now</a>
  </div>
</div>

<h1 id="dernieres-nouvelles"> All of our robots </h1>
<div class="container">
  <div class="row">
    <% @robots.each do |robot| %>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.2)), url(<%= image_path 'Fotolia_31943186_Subscription_XL-1078x800.jpg' %>);">
            <span class="card-category"><%= link_to robot.name, robot_path(robot) %></span>
          </div>
          <div class="card-footer">
            <br>
            price: <%= robot.price %>
            <br>
            functions: <%= robot.functions %>
            <br>
            caracteristics: <%= robot.caracteristics %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/robots/show.html.erb
<div class="container">

    <div class="wrapper">
      <div class="item">
        <h3><%= @robot.name %></h3>
        <p><%= @robot.functions %></p>
        <p><%= @robot.caracteristics %></p>
      </div>
      <div class="item">
        <%= image_tag "BB-8_Clean_legal_line_1024x1024.jpg", id: "robot-picture" %>
        <div class="price-and-button">
          <p class="prix">price: <%= @robot.price %> $</p>
          <a href="#" class="btn btn-info gauche">Book me</a>
        </div>
    </div>
</div>
  <hr>
  <div>formulaire saisi avec un collapse sur le bouton "Book me"
    <h4>When do you want to book this robot ?</h4>
    <%= simple_form_for (@booking) do |f| %>
      <%= f.text_field :beginning_of_rental, hide_label: true, class: 'datepicker' %></p>
      <%= f.text_field :end_of_rental, hide_label: true, class: 'datepicker' %></p>
      <%= f.submit "finalize the order", class: "btn btn-primary" %>
    <% end %>
  </div>
  <hr>
  <div>
    <div>Reviews</div>
    <div>Reviews'cards</div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
<div class="left">
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 100 %>
  <% end %>
  <%= form_tag robots_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a robot"
      %>
  <% end %>
  </div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "if_profile-filled_299075.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to my_robots_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container">
  <div class="user-card">
    <div class="user-picture-and-button">

    </div>
    <div class="user-details">
      <h3><%= @user.email %></h3>
    </div>
  </div>
  <div>
    <% @owner = @user.owner %>
    <h4><%= @owner %></h4>
  </div>
  <hr>
  <div class="robots-owned-or-bookings-maid">
  </div>
</div>